### ISSUE TITLE
csvcubed build validation-errors.json file path is invalid

### ISSUE THREAD

**Issue by GDonRanasinghe** [GSS-Cogs/csvcubed#565] opened 2022-08-03 16:54 UTC
I ran the `csvcubed build` cmd with the erroneous input below. The command I ran is 
`csvcubed build csv/errorneous_input/csv_errorneous.csv --out out/errorneous_input/csv_errorneous --validation-errors-to-file`

```csv
Dimension,Value,Measure,Unit
A,,Length,cm
B,,Length,cm
C,,Length,cm
D,,Length,cm
E,,Length,cm
```
Then I got the below exception. As shown in the exception, the path `csvcubed build` is looking at for the validation-errors.json seems to be wrong. I was expecting for it to look at `out/errorneous_input/csv_errorneous/validation-errors.json`.

`2022-08-03 16:53:14,530 - csvcubed.cli.build - ERROR - Validation Error: Observed values missing in 'Value' on rows: {0, 1, 2, 3, 4} (build.py:87)
2022-08-03 16:53:14,530 - csvcubed.cli.build - ERROR - More information: http://purl.org/csv-cubed/err/obsv-val-mis (build.py:89)
2022-08-03 16:53:14,531 - csvcubed.cli.entrypoint - CRITICAL - Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/csvcubed/cli/entrypoint.py", line 94, in build_command
    build(
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/csvcubed/cli/build.py", line 59, in build
    with open(output_directory / validation_errors_file_out, "w+") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'out/errorneous_input/csv_errorneous/out/errorneous_input/csv_errorneous/validation-errors.json'
 (log.py:109)`.

**Comment by robons** [comment] 2022-08-16 10:02
Closing as duplicate of #570

**Closed by robons** 2022-08-16 10:02 UTC
Labels: bug, Needs Estimation, Needs Discussion
