### ISSUE TITLE
Creating a User Guide to writing a qube-config.json file

### ISSUE THREAD

**Issue by SarahJohnsonONS** [GSS-Cogs/csvcubed#706] opened 2023-01-24 12:18 UTC
Following on from the completion of #648, the following suggestions have been identified to improve the user guidance on writing a qube-config.json file:

[General comments:](https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/qube-config/)

- [ ] Resolve whether the terminology is “qube-config” or “cube-config” (all pages) (include in [Confluence Style Guide](https://confluence.ons.gov.uk/display/PHEM/Style+Guide))
- [ ] Resolve whether csv and uri should be capitalised or not (all pages) (include in [Confluence Style Guide](https://confluence.ons.gov.uk/display/PHEM/Style+Guide))
- [ ] Include a link to the current qube-config schema
- [ ] Use one data set throughout guide (if feasible)

[Column definitions](https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/qube-config/#column-definitions)

- [ ] “Using existing columns” section could do with better explanations - e.g. “Unless the component being reused is a literal attribute and you're providing a "data_type" key-value pair, any other key-value pairs provided will change the column to a new component which will extend the linked parent component.”
- [ ] For components other than Dimension - make it clearer that “type” will default to “dimension” unless explicitly stated
- [ ] Include explanations about New/Existing - existing where?
- [ ] Reorder tables to match the order in the schema

[Shared column configuration option](https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/qube-config/#shared-column-configuration-options)

- [ ] Repetitive - could be incorporated into individual sections

[Measures and Units](https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/qube-config/#measures-and-units)

- [ ] Make it clearer that the properties in the table go inside the “values” property for measures/units

The new User Guide should link to the [existing reference documentation](https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/qube-config/) where appropriate. The reference documentation could be further amended to minimise repetition between the two documents and direct users to the User Guide for configuration examples.

**Comment by robons** [comment] 2023-02-21 10:47
Closing as a duplicate of #520.

**Closed by robons** 2023-02-21 10:47 UTC
