### ISSUE TITLE
Document code list config

### ISSUE THREAD

**Issue by GDonRanasinghe** [GSS-Cogs/csvcubed#517] opened 2022-06-08 20:47 UTC
We need to document how a user can define a code list using the code list config. The following need to be documented:

1. How to create an inline code list within the cube config using the code list schema.
2. How to create a separate code list within the cube config using the code list schema.

**Comment by robons** [comment] 2022-07-05 09:39
Dupe of #524

**Closed by robons** 2022-07-05 09:39 UTC
